
[package]
name = "totalmapper"
version = "1.5.0"
authors = ["Owen Healy <owen@owenehealy.com>"]
edition = "2018"
description = "Remaps keycodes in the Linux input event system based on a simple, JSON-defined list of mappings."
license = "MIT"

[package.metadata.deb]
section = "utils"
priority = "optional"
assets = [
  ["target/release/totalmapper", "usr/bin/", "755"],
]

[dependencies]
nix = { version = "0.31.3", features = ["fs"] }
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
libc = "0.2.180"
uinput-sys = "0.1.7"
num-traits = "0.2.19"
num-derive = "0.4.2"
clap = "4.6.1"
lazy_static = "1.5.0"
ioctls = "0.6.2"
mio = { version = "1.2.1", features = ["os-ext"] }
inotify = "0.11.2"
strum = { version = "0.28.0", features = ["derive"] }
wildmatch = "2.6.1"

[dev-dependencies]
similar = "3.1.1"
colored = "3.1.1"

