
name: make-relase-3

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  buildJob:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install raku
        run: sudo apt-get install rakudo -y
      - name: Install aarch64 gcc
        run: sudo apt-get install gcc-aarch64-linux-gnu -y
      - name: Install aarch64 target
        run: rustup target add aarch64-unknown-linux-musl
      - name: Install amd64 target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build raw amd64
        run: ./release-scripts/build-raw-amd64
      - name: Build raw aarch64
        run: ./release-scripts/build-raw-aarch64
      - name: Build Focal
        run: ./release-scripts/build-focal
      - name: Build Jammy
        run: ./release-scripts/build-jammy
      - name: Build Noble
        run: ./release-scripts/build-noble
      - name: Make release
        uses: softprops/action-gh-release@v0.1.14
        with:
          fail_on_unmatched_files: true
          files: |
            raw-building/totalmapper-*-aarch64-*.tar.gz
            raw-building/totalmapper-*-amd64-*.tar.gz
            build/debs/totalmapper_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
