
name: make-relase

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  buildJob:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install raku
        run: sudo apt-get install rakudo -y
      - name: Install aarch64 gcc
        run: sudo apt-get install gcc-aarch64-linux-gnu -y
      - name: Install aarch64 target
        run: rustup target add aarch64-unknown-linux-musl
      - name: Install amd64 target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build raw amd64
        run: ./release-scripts/build-raw-amd64
      - name: Build raw aarch64
        run: ./release-scripts/build-raw-aarch64
      - name: Build debs
        run: ./release-scripts/build-deb-in-docker
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            raw-building/totalmapper-static-linux-aarch64-*.tar.gz
            raw-building/totalmapper-*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
